<a href="https://colab.research.google.com/github/MathewS424/DeepLearning_with_PyTorch/blob/main/00_PyTorch_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [21]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor, random_tensor.shape, random_tensor.size()

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 torch.Size([7, 7]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [23]:
# Create another random tensor
random_tensor_3 = torch.rand(1, 7).T
print(random_tensor_3.shape)

# Perform matrix multiplication
matrix_mul = torch.matmul(random_tensor, random_tensor_3)
matrix_mul, matrix_mul.shape

torch.Size([7, 1])


(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [26]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_2 = torch.rand(7, 7)
random_tensor_3 = torch.rand(1, 7)
random_tensor_3 = random_tensor_3.T

print(random_tensor_2.shape)
print(random_tensor_3.shape)

# Matrix multiply tensors
matrix_mul = torch.matmul(random_tensor_2, random_tensor_3)
matrix_mul, matrix_mul.shape

torch.Size([7, 7])
torch.Size([7, 1])


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [27]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.manual_seed(0)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
random_tensor_0 = torch.rand(size=(2, 3), device=device)
random_tensor_1 = torch.rand(2, 3).to(device)
print(random_tensor_0)
print(random_tensor_1)

Device: cpu
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [35]:
# Perform matmul on tensor_A and tensor_B
MATRIX_MUL = torch.matmul(random_tensor_0, random_tensor_1.T)
MATRIX_MUL, MATRIX_MUL.shape

(tensor([[0.9722, 0.6174],
         [0.6292, 0.4455]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [42]:
# Find max
maxi = torch.max(MATRIX_MUL)
print(maxi)
# Find min
mini = torch.min(MATRIX_MUL)
print(mini)

tensor(0.9722)
tensor(0.4455)


### 9. Find the maximum and minimum index values of the output of 7.

In [43]:
# Find arg max
arg_max = torch.argmax(MATRIX_MUL)
print(arg_max)

# Find arg min
arg_min = MATRIX_MUL.argmin()
print(arg_min)

tensor(0)
tensor(3)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [47]:
# Set seed
torch.manual_seed(42)

# Create random tensor
random_tensor_10 = torch.rand(size=(1, 1, 1, 10))


# Remove single dimensions
remove_dim = random_tensor_10.squeeze()


# Print out tensors and their shapes
print(f"{random_tensor_10}  {random_tensor_10.shape}")
print(f"{remove_dim}  {remove_dim.shape}")

tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
           0.9408, 0.1332]]]])  torch.Size([1, 1, 1, 10])
tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332])  torch.Size([10])
