<a href="https://colab.research.google.com/github/MathewS424/DeepLearning_with_PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

[Resourse NoteBook](https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


# Introduction to Tensor

Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python as int
item = scalar.item()
item

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape   # Row x Col ,2X2

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [26]:
tensor1 = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]],

                       [[11,22,33],
                        [33,64,93],
                       [23,42,51]]])
tensor1

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[11, 22, 33],
         [33, 64, 93],
         [23, 42, 51]]])

In [27]:
tensor1.ndim


3

In [28]:
tensor1.shape

torch.Size([2, 3, 3])

In [34]:
print(tensor1[1])
print(tensor1[0])
print(tensor1[1][2])
print(tensor1[1][2][2])

tensor([[11, 22, 33],
        [33, 64, 93],
        [23, 42, 51]])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([23, 42, 51])
tensor(51)


# Explanation
Shape: The shape [4, 5, 3] means:

4 blocks (first dimension)  
5 rows in each block (second dimension)   
3 columns in each row (third dimension)   
Last Two Elements Are Not the Same: The rows within each block are not identical, which satisfies the condition that "the last two elements are not the same."

In [42]:
import torch

tensor2 = torch.tensor([
    [[1, 2, 3],   # Block 1
     [3, 6, 9],
     [2, 4, 5],
     [5, 10, 15],
     [7, 14, 21]],

    [[11, 22, 33],  # Block 2
     [33, 64, 93],
     [23, 42, 51],
     [44, 88, 132],
     [9, 18, 27]],

    [[11, 22, 33],  # Block 3
     [33, 1, 93],
     [23, 42, 51],
     [15, 30, 45],
     [6, 12, 18]],

    [[11, 22, 33],  # Block 4
     [33, 64, 93],
     [23, 42, 51],
     [14, 28, 42],
     [3, 6, 9]]
])
print(tensor2.ndim)   # Output the number of dimensions
print(tensor2.shape)  # Output the shape of the tensor
print(tensor2)        # Output the tensor itself

print("_________________________________________________________________________")

tensor2 = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]],

                       [[11,22,33],
                        [33,64,93],
                       [23,42,51]],

                        [[11,22,33],
                        [33,1,93],
                       [23,42,51]],

                        [[11,22,33],
                        [33,64,93],
                       [23,42,51]]])

print(tensor2.ndim)
print(tensor2.shape)
print(tensor2)

3
torch.Size([4, 5, 3])
tensor([[[  1,   2,   3],
         [  3,   6,   9],
         [  2,   4,   5],
         [  5,  10,  15],
         [  7,  14,  21]],

        [[ 11,  22,  33],
         [ 33,  64,  93],
         [ 23,  42,  51],
         [ 44,  88, 132],
         [  9,  18,  27]],

        [[ 11,  22,  33],
         [ 33,   1,  93],
         [ 23,  42,  51],
         [ 15,  30,  45],
         [  6,  12,  18]],

        [[ 11,  22,  33],
         [ 33,  64,  93],
         [ 23,  42,  51],
         [ 14,  28,  42],
         [  3,   6,   9]]])
_________________________________________________________________________
3
torch.Size([4, 3, 3])
tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[11, 22, 33],
         [33, 64, 93],
         [23, 42, 51]],

        [[11, 22, 33],
         [33,  1, 93],
         [23, 42, 51]],

        [[11, 22, 33],
         [33, 64, 93],
         [23, 42, 51]]])


# Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

**Start with random numbers-> look at data-> update random numbers-> look at data-> update random numbers**

In [48]:
# Create a random tensor of size(3, 4), size(1, 5, 4), size(5) ..etc
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2539, 0.2252, 0.9329, 0.7110],
        [0.3998, 0.4173, 0.0929, 0.9306],
        [0.5337, 0.5801, 0.4030, 0.4430]])

In [49]:
random_tensor.ndim

2

In [51]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel(R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# ZEROES AND ONES

In [52]:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
ones = torch.ones(size=(2,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [55]:
ones*random_tensor

tensor([[[0.2539, 0.2252, 0.9329, 0.7110],
         [0.3998, 0.4173, 0.0929, 0.9306],
         [0.5337, 0.5801, 0.4030, 0.4430]],

        [[0.2539, 0.2252, 0.9329, 0.7110],
         [0.3998, 0.4173, 0.0929, 0.9306],
         [0.5337, 0.5801, 0.4030, 0.4430]]])

In [56]:
print(random_tensor.dtype)
print(ones.dtype)
print(zeroes.dtype)

torch.float32
torch.float32
torch.float32


# Creating a range of tensors and tensors-like

In [63]:
# Use torch.range()
print(torch.range(1, 10))
print(torch.arange(11, 20))
print(torch.arange(start=0, end=1000, step=77))
print(torch.arange(start=0, end=11, step=1))
print("\n")

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])




<ipython-input-63-c2417c2d234e>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(1, 10))


In [64]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=random_tensor)  # Create a tensor of all zeros with the same shape as random_tensor
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Tensor datatypes
**Common Issues or Error that occurs**   
      1.Tensors not right datatype - to troubleshoot tensor.dtype     
      2.Tensors not right shape - to troubleshoot tensor.shape  
      3.Tensors not on the right device - to troubleshoot tensor.device

In [70]:
# Float 32 tensor by default
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [71]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # what datatype is the tensor (e.g. float32 or float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [68]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [72]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [73]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [74]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Tensor Attribute

In [75]:
# Create some tensor and Tensor attributes
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3581, 0.4772, 0.2741, 0.8349],
        [0.5795, 0.5094, 0.4516, 0.8881],
        [0.7994, 0.7637, 0.2646, 0.5452]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensors (tensor operations)

In [81]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [82]:
# Multiply tensor by 10
print(tensor * 10)
tensor = tensor * 20
tensor

tensor([10, 20, 30])


tensor([20, 40, 60])

In [83]:
# Try out PyTorch inbuilt functions
torch.mul(tensor, 10)

tensor([200, 400, 600])

# Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:  
1.Element wise multplication  
2.Matrix multiplication(dot product)

There are two main rules that performinng matrix multi needs to satisfy:
1. The **inner dimentions** must match:     
  (3, 2) @ (3, 2) - won't work      
  (2, 3) @ (3, 2) - will work     
  (3, 2) @ (2, 3) - will work

2.  The result matrix has the shape of the **outer dimentions**   
  (2, 3) @ (3, 2) -> (2, 2)   
  (3, 2) @ (2, 3) -> (3, 3)

In [84]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([20, 40, 60]) * tensor([20, 40, 60])
Equals: tensor([ 400, 1600, 3600])


In [86]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(5600)

In [87]:
tensor @ tensor

tensor(5600)

In [88]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [90]:
print(torch.matmul(torch.rand(3, 2), torch.rand(2, 3)))
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape


tensor([[0.3666, 0.2858, 0.5569],
        [0.0120, 0.0265, 0.0998],
        [0.3421, 0.2518, 0.4491]])


torch.Size([3, 3])

# One of the most common errors in deep learning: shape errors

In [91]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [92]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To Fix our tensor shape issues, we can manipulate the shape of one of ours tensors using **transpose**
A **transpose** switches the axes or dimentions of a given tensor

In [98]:
print(f"Oringinal:\n\t{tensor_B}")
print(f"Transpose:\n\t{tensor_B.T}")
print(f"Shape:\t{tensor_B.T.shape}")

Oringinal:
	tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
Transpose:
	tensor([[ 7,  8,  9],
        [10, 11, 12]])
Shape:	torch.Size([2, 3])


In [99]:
# The matrix multi operation works when tensor_B is transposed
torch.mm(tensor_A, tensor_B.T) #3X2 2X3 ->3X3

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Find the min, max, mean, sum, etc (tensor aggregation)

In [108]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [101]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [102]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [103]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [104]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [105]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Positional Min and Max
**argmin(), argmax()**

In [106]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [110]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor wheere the minimum value occur
x.argmin()

tensor(0)

In [111]:
x[0]

tensor(1)

In [112]:
# Find the position in tensor that has the maximum value with argmin() -> returns index position of target tensor wheere the minimum value occur
x.argmax()

tensor(9)

In [113]:
x[9]

tensor(91)

# Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Retuen a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimentions from a tensor
* Unsqueeze - add a `1` dimention to a target tensor
*Permute- Return a view of the input with dimentions permuted (swapped) in a certain way

In [127]:
# Create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [120]:
# Add an extra dimention
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 10

In [122]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [123]:
# Change the view
z = x.view(1, 7)
z, z.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 10

In [128]:
# Change the view
z = x.view(1, 10)
z, z.shape
# Changing z changes x (because a view of a tensor shares the same memort as the original tensor)

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [129]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [126]:
z[0] = 4
z, x

(tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]]),
 tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]))

In [138]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [139]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [140]:
x_stacked = torch.stack([x, x, x, x, x, x, x], dim=0)  # 7 tensor stack
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [141]:
x_stacked = torch.stack([x, x, x, x, x, x, x], dim=1)  # 7 tensor stack
x_stacked

tensor([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.,  9.,  9.,  9.],
        [10., 10., 10., 10., 10., 10., 10.]])

In [142]:
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [143]:
x_stacked = torch.hstack([x, x, x, x, x, x, x])  # 7 tensor stack
x_stacked  # -> NOT SAME AS x_stacked = torch.stack([x, x, x, x, x, x, x], dim=1) dimention 1

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,
         5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
         9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,
         3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,
         7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [144]:
x_stacked = torch.vstack([x, x, x, x, x, x, x])  # 7 tensor stack , dim = 0 = vstack
x_stacked  # -> same as  x_stacked = torch.stack([x, x, x, x, x, x, x], dim=0)

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [148]:
# Squeeze - removes all 1 dimentionx
x_reshaped = x.reshape(1, 10)
x_reshaped

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [149]:
x_reshaped.shape

torch.Size([1, 10])

In [153]:
print(x_reshaped.squeeze())
x_reshaped.squeeze().shape  # remove 1 dimention

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


torch.Size([10])

In [155]:
# Squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimentions from x_reshaped -remove one square bracket
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [157]:
# Unsqeeze() - adda a single dimention to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

# Add an extra dimention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])

New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [158]:
# Peermute - rearranges the dimentions of a target tensor in a specified order , Returns a view
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [162]:
print(x.size())
print(x.permute(2, 0, 1).size())
torch.permute(x, (2, 0, 1)).shape

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


torch.Size([5, 2, 3])

In [166]:
x_original = torch.rand((224, 224, 3))  # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim)  order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [color_channels, height, width] , x_original and x_permuted same memory or same view

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [167]:
x_original[0, 0, 0] = 728218  # x_original and x_permuted same memory or same view
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

# Slicing in detail

### Scenario 1: Slicing Multiple Rows and Columns

Suppose we have a 2D tensor, and we want to access and modify a specific subset of rows and columns.

```python
import torch

# Create a 2D tensor (3 rows, 4 columns)
x = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("Original x tensor:\n", x)

# Slice to get a submatrix (2 rows, 2 columns)
submatrix = x[:2, 1:3]  # First 2 rows, columns 1 and 2
print("\nSubmatrix (first 2 rows, columns 1 and 2):\n", submatrix)

# Modify the submatrix
submatrix[:, :] = 0  # Set all elements of the submatrix to 0
print("\nModified submatrix:\n", submatrix)
print("\nModified x tensor:\n", x)
```

**Output**:
```
Original x tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Submatrix (first 2 rows, columns 1 and 2):
 tensor([[2, 3],
        [6, 7]])

Modified submatrix:
 tensor([[0, 0],
        [0, 0]])

Modified x tensor:
 tensor([[ 1,  0,  0,  4],
        [ 5,  0,  0,  8],
        [ 9, 10, 11, 12]])
```

### Explanation:

- **`x[:2, 1:3]`**: This slices the first two rows (`:2`) and the second and third columns (`1:3`), giving us a 2x2 submatrix.
- **Modification**: Setting `submatrix[:, :] = 0` changes all elements in the submatrix to `0`. Since `submatrix` is a view, this change is reflected in the original tensor `x`.

### Scenario 2: Selecting Specific Rows or Columns

Let's say we want to select and modify specific rows or columns in a tensor.

```python
import torch

# Create a 2D tensor (4 rows, 4 columns)
x = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

print("Original x tensor:\n", x)

# Select the second row
second_row = x[1, :]
print("\nSecond row:\n", second_row)

# Select the third column
third_column = x[:, 2]
print("\nThird column:\n", third_column)

# Modify the second row
x[1, :] = torch.tensor([0, 0, 0, 0])
print("\nModified x tensor after changing the second row:\n", x)

# Modify the third column
x[:, 2] = torch.tensor([-1, -2, -3, -4])
print("\nModified x tensor after changing the third column:\n", x)
```

**Output**:
```
Original x tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Second row:
 tensor([5, 6, 7, 8])

Third column:
 tensor([ 3,  7, 11, 15])

Modified x tensor after changing the second row:
 tensor([[ 1,  2,  3,  4],
        [ 0,  0,  0,  0],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Modified x tensor after changing the third column:
 tensor([[ 1,  2, -1,  4],
        [ 0,  0, -2,  0],
        [ 9, 10, -3, 12],
        [13, 14, -4, 16]])
```

### Explanation:

- **`x[1, :]`**: Selects the entire second row.
- **`x[:, 2]`**: Selects the entire third column.
- **Modification**: Changing the selected row or column directly modifies the original tensor.

### Scenario 3: Slicing with Negative Indices

Negative indices can be used to slice from the end of a tensor.

```python
import torch

# Create a 1D tensor
x = torch.tensor([1, 2, 3, 4, 5, 6])

print("Original x tensor:", x)

# Select the last three elements
last_three = x[-3:]
print("\nLast three elements:", last_three)

# Modify the last three elements
x[-3:] = torch.tensor([7, 8, 9])
print("\nModified x tensor:", x)
```

**Output**:
```
Original x tensor: tensor([1, 2, 3, 4, 5, 6])

Last three elements: tensor([4, 5, 6])

Modified x tensor: tensor([1, 2, 3, 7, 8, 9])
```

### Explanation:

- **`x[-3:]`**: Slices the last three elements of the tensor.
- **Modification**: Changing `x[-3:]` directly updates the last three elements of the original tensor.

### Scenario 4: Multi-Dimensional Tensor Slicing

For more complex scenarios, let's consider a 3D tensor.

```python
import torch

# Create a 3D tensor (2 blocks, 3 rows, 4 columns)
x = torch.tensor([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],

                  [[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]]])

print("Original x tensor:\n", x)

# Select the first block
first_block = x[0, :, :]
print("\nFirst block:\n", first_block)

# Select the second row of the second block
second_row_second_block = x[1, 1, :]
print("\nSecond row of the second block:\n", second_row_second_block)

# Modify the first row of the first block
x[0, 0, :] = torch.tensor([10, 20, 30, 40])
print("\nModified x tensor after changing the first row of the first block:\n", x)
```

**Output**:
```
Original x tensor:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

First block:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Second row of the second block:
 tensor([17, 18, 19, 20])

Modified x tensor after changing the first row of the first block:
 tensor([[[10, 20, 30, 40],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
```

### Explanation:

- **`x[0, :, :]`**: Selects the entire first block (all rows and columns).
- **`x[1, 1, :]`**: Selects the second row of the second block.
- **Modification**: Changing the first row of the first block directly updates the tensor.

### Summary of Slicing:

1. **`:`**: Selects all elements along a dimension.
2. **Specific index (`n`)**: Selects a particular element at index `n`.
3. **Negative indices (`-n`)**: Selects elements counting from the end.
4. **Slices (`start:stop`)**: Selects a range of elements.

Understanding and mastering slicing is crucial for effectively manipulating tensors in PyTorch, especially when working with multi-dimensional data like images or sequences.